name: NodeJS Lint, Build and Test

on:
  push:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.ts'
      - 'tests/*.ts'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.8.1
      with:
        node-version: '20.x'
    - run: |
        npm i
        npm ci
        npm run lint
        npm run build
