name: NPM publish CD workflow

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:
  build:

    # Run on latest version of ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.8.1
      with:
        node-version: '15.x'
        # Specifies the registry, this field is required!
        registry-url: https://registry.npmjs.org/
    # clean install of your projects' deps. We use "npm ci" to avoid package lock changes
    - run: npm ci
    # set up git since we will later push to the repo
    - run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
    # upgrade npm version in package.json to the tag used in the release.
    - run: |
        TAG=${GITHUB_REF#refs/tags/v}
        npm version --allow-same-version --no-git-tag-version ${TAG}
    # build the project
    - run: npm run build
    # publish to NPM
    - run: npm publish --access public
      env:
        # Use a token to publish to NPM.
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
